# Generated by Django 3.1.2 on 2020-10-25 19:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='screen1',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='screen2',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Picture'),
        ),
    ]
