# Generated by Django 3.1.2 on 2020-10-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awords', '0003_auto_20201028_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-sitename']},
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='sitename',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='link',
            new_name='url',
        ),
    ]
