# Generated by Django 3.1.2 on 2020-10-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awords', '0005_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
