# Generated by Django 3.1.2 on 2020-10-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awords', '0006_auto_20201028_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
    ]
